language: node_js
node_js:
  - "14"
  - "12"
  - "10"
  - "8"
matrix:
  fast_finish: true
script: if [ $(echo "${TRAVIS_NODE_VERSION}" | cut -d'.' -f1) -ge 6 ]; then
          npm run cover;
        else
          npm test;
        fi
os:
  - linux
  - osx
